---
- hosts: all
  remote_user: root
  tasks:
          # upload ssh key                
                     - authorized_key:
                        user: tose 
                        state: present
                        manage_dir: yes
                        key: "{{ lookup('file', '/home/tose/.ssh/id_rsa.pub') }}"

